### ISSUE TITLE
Maybe add runtime validation for name as the split breaks it if name isn't provided 

### ISSUE THREAD

**Issue by danielkellyio** [carwack/tiny-forge-ui#1]
I know the TS makes it required but if run in browser, the error of Cannot call .split on undefined is a little cryptic. Would be nice to have a  runtime check on name and throw an error saying it's required if not provided

**Comment by danielkellyio** [comment]
(in solution)

**Comment by Sybren-crwk** [comment]
Great idea, added to the solution! 👏
